language: python
python: "3.6"

script:
  - mkdocs build --clean

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GH_TOKEN
  repo: tomochain/docs
  target-branch: gh-pages
  local-dir: site
  fqdn: docs.tomochain.com
  on:
    branch: master
