site_name: Tomochain Documentation

theme:
  name: 'material'
  custom_dir: material_override
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True 
    - fontawesome_markdown
    - markdown.extensions.extra
    - markdown.extensions.toc:
        permalink: True

extra_javascript:
    - js/MathJax.js?config=TeX-AMS_HTML

extra_css:
    - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css
    - css/style.css

extra:
    social:
        - type: 'github'
          link: 'https://github.com/tomochain'
        - type: 'twitter'
          link: 'https://twitter.com/tomochainANN'
        - type: 'reddit'
          link: 'https://www.reddit.com/r/Tomochain/'
        - type: 'facebook'
          link: 'https://www.facebook.com/tomochainofficial/'
        - type: 'telegram'
          link: 'https://t.me/tomochain'
        - type: 'medium'
          link: 'https://medium.com/tomochain'

site_url: https://docs.tomochain.com
repo_url: https://github.com/tomochain/docs
repo_name: tomochain/docs

pages:
    - Introduction: index.md
    - Getting started: started.md    
    - Technical Whitepaper: whitepaper.md
    - Important Links: links.md
    - About: about.md
