site_name: Tao Documentation
site_description: Tao aims to be a public EVM-compatible blockchain with the following advantages as low transaction fee, fast confirmation time, double validation.

theme:
  name: 'mkdocs'
  custom_dir: material_override
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'
  feature:
    tabs: false

plugins:
  - redirects
  - search

redirects:
  'taoscan/features/index': 'products/taoscan/features/index'
  'shifu/features/index': 'products/shifu/features/index'

markdown_extensions:
  - admonition
  - mdx_math:
      enable_dollar_delimiter: True
  - markdown.extensions.extra
  - markdown.extensions.toc:
      permalink: True
  - codehilite:
      guess_lang: false

extra_javascript:
    - js/MathJax.js?config=TeX-AMS_HTML

extra_css:
    - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css
    - css/style.css

extra:
    disqus:
    social:
        - type: 'github'
          link: 'https://github.com/taoblockchain'
        - type: 'twitter'
          link: 'https://twitter.com/taoblockchain'
        - type: 'telegram'
          link: 'https://t.me/taoblockchain'
        - type: 'medium'
          link: 'https://medium.com/taoblockchain'

site_url: https://docs.tao.network
repo_url: https://github.com/taoblockchain/docs
repo_name: tao/docs
google_analytics: ['UA-124597188-1', 'docs.tao.network']

nav:
    - Get started:
      - Introduction: index.md
      - Products overview: get-started/productoverview.md
      - How to read: get-started/how_to_read.md
      - Connect your wallet: get-started/wallet.md
      - Voting: get-started/voting.md
      - Networks: general/networks.md
      - FAQ: general/faq.md
    # - Tao client:
    #   - Getting started: misc/wip.md
    #   - Contributing: misc/wip.md
    - Masternode/DEX:
      - Requirements: masternode/requirements.md
      - Detailed guide: masternode/masternode-setup-guide.md
      - Running a node with:
        - Binary: masternode/taonative.md
        - Create-tao-masternode: masternode/create-tao-masternode.md
        - Tmn: masternode/tmn.md
        - Docker: masternode/docker.md
      - Applying for Masternode Candidacy: masternode/applying.md
      - Chaindata Snapshots: masternode/snapshot.md
      - Run a full node in testnet: get-started/run-node.md
      - Apply your node in testnet: get-started/apply-node.md
      - Running a Waihui Mongodb fullnode: masternode/waihui-fullnode.md
      - Running a Waihui DEX: masternode/waihui-sdk.md
  #   - Contributing: misc/wip.md
    #   - FAQ: misc/wip.md
    - Developers guide:
        - Networks: general/networks.md
        - Integrations:
          - TAO Exchange/Wallet: developers/integrations.md
          - Tao Staking Governance: developers/staking-integrations.md
          - TRC1 Exchange/Wallet: developers/trc1-integrations.md
          - TRC2 Exchange/Wallet: developers/trc2-integrations.md
        - Working with Tao:
           - Tao private testnet setup: developers/tutoprivatenet.md
           - Useful manual CLI commands: developers/clicommands.md
        - DApps on Tao:
           - Deploy DApp on Tao: developers/dappdeploytuto.md
           - Deploy an ICO smart contract: developers/icosmartcontract.md
        - API Documentation: https://apidocs.tao.network
    - Whitepapers/Specs:
      - Technical whitepaper: wp-and-research/technical-whitepaper.md
      - Sharding design paper: wp-and-research/sharding-paper.md
      - Economics paper: wp-and-research/economics-paper.md
      - Standard & Specification:
          - TRC2 Specification: wp-and-research/specs/trc2_standard.md
      - TaoP whitepaper: wp-and-research/privacy.md
    - Products:
      - Shifu: products/shifu/features.md
    #   - Contributing: misc/wip.md
      - TaoScan: products/taoscan/features.md
      - TaoWallet:
        - Features: products/taowallet/features.md
        - Voting with TaoWallet: products/taowallet/voting.md
        - Terms & Privacy: products/taowallet/terms.md
      - TaoBridge:
        - FAQ: products/taobridge/faq.md
      - TaoIssuer:
        - Overview: products/taoissuer/index.md
        - Term Of Condition: products/taoissuer/termofcondition.md
        - Policy Privacy: products/taoissuer/policyprivacy.md
    #   - Getting started: misc/wip.md
    #   - Contributing: misc/wip.md
copyright: If you wish to improve this site, please <a href="https://github.com/taoblockchain/docs/issues/new"><i class="fa fa-github"></i> open an issue</a> or <a href="https://github.com/taoblockchain/docs/compare"><i class="fa fa-github"></i> send a pull request</a>.<br>Ta0Docs v0.1.0. Tao Project 2020.
