site_name: Tomochain Documentation

theme:
  name: 'material'

pages:
    - Introduction: index.md
    - Getting started: started.md    
    - Technical Whitepaper: whitepaper.md
    - Important Links: links.md
    - About: about.md
