site_name: Tomochain Documentation
site_description: The most efficient platform for token economy

theme:
  name: 'material'
  custom_dir: material_override
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
    - fontawesome_markdown
    - markdown.extensions.extra
    - markdown.extensions.toc:
        permalink: True

extra_javascript:
    - js/MathJax.js?config=TeX-AMS_HTML

extra_css:
    - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css
    - css/style.css

extra:
    social:
        - type: 'github'
          link: 'https://github.com/tomochain'
        - type: 'twitter'
          link: 'https://twitter.com/tomochainANN'
        - type: 'reddit'
          link: 'https://www.reddit.com/r/Tomochain/'
        - type: 'facebook'
          link: 'https://www.facebook.com/tomochainofficial/'
        - type: 'telegram'
          link: 'https://t.me/tomochain'
        - type: 'medium'
          link: 'https://medium.com/tomochain'

site_url: https://docs.tomochain.com
repo_url: https://github.com/tomochain/docs
repo_name: tomochain/docs
google_analytics: ['UA-124597188-1', 'docs.tomochain.com']

pages:
    - Introduction: index.md
    - Get started:
        - Voter's Guide: get-started/started.md
        - Testnet: get-started/testnet.md
        - Running a node: get-started/run-node.md
        - Apply your node as a masternode: get-started/apply-masternode.md
        # - Create your own network: get-started/private-network.md
    - Wallets:
        - Metamask: wallets/metamask.md
        - TomoWallet: wallets/tomowallet.md
    - Technical Whitepaper: whitepaper.md
    - FAQ:
        - General: faq/general.md
        - Tomochain: faq/tomochain.md
        - Other: faq/other.md
    - Use Cases: use-cases/index.md
    - Contribution:
        - Github: contribution/github.md
        - Team: contribution/team.md
    - Important Links: links.md
    - About: about.md

copyright: If you wish to improve this site, please <a href="https://github.com/tomochain/docs/issues/new"><i class="fa fa-github"></i> open an issue</a> or <a href="https://github.com/tomochain/docs/compare"><i class="fa fa-github"></i> send a pull request</a>.<br>tomodocs v0.1.0. Tomochain Project 2018.
