site_name: Tomochain Documentation

theme:
  name: 'material'
  custom_dir: material_override

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True 
    - fontawesome_markdown
    - markdown.extensions.extra

extra_javascript:
    - js/MathJax.js?config=TeX-AMS_HTML

extra_css:
    - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css

pages:
    - Introduction: index.md
    - Getting started: started.md    
    - Technical Whitepaper: whitepaper.md
    - Important Links: links.md
    - About: about.md
