site_name: TomoChain Documentation
site_description: TomoChain aims to be a public EVM-compatible blockchain with the following advantages as low transaction fee, fast confirmation time, double validation.

theme:
  name: 'material'
  custom_dir: material_override
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'
  feature:
    tabs: true

plugins:
  - redirects

redirects:
  'tomoscan/features/index': 'products/tomoscan/features/index'
  'tomomaster/features/index': 'products/tomomaster/features/index'

markdown_extensions:
  - admonition
  - mdx_math:
      enable_dollar_delimiter: True
  - markdown.extensions.extra
  - markdown.extensions.toc:
      permalink: True
  - codehilite:
      guess_lang: false

extra_javascript:
    - js/MathJax.js?config=TeX-AMS_HTML

extra_css:
    - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css
    - css/style.css

extra:
    disqus:
    social:
        - type: 'github'
          link: 'https://github.com/tomochain'
        - type: 'twitter'
          link: 'https://twitter.com/tomochainANN'
        - type: 'reddit'
          link: 'https://www.reddit.com/r/Tomochain/'
        - type: 'facebook'
          link: 'https://www.facebook.com/tomochainofficial/'
        - type: 'telegram'
          link: 'https://t.me/tomochain'
        - type: 'medium'
          link: 'https://medium.com/tomochain'

site_url: https://docs.tomochain.com
repo_url: https://github.com/tomochain/docs
repo_name: tomochain/docs
google_analytics: ['UA-124597188-1', 'docs.tomochain.com']

nav:
    - General:
      - Introduction: index.md
      - Use cases: general/use-cases.md
      - Networks: general/networks.md
      - FAQ: general/faq.md
      - About: general/about.md
    - Get started:
      - Overview:
        - Products overview: get-started/productoverview.md
        - How to read: get-started/how_to_read.md
      - Beginners Tutorials:
        - Connect your wallet: get-started/wallet.md
        - Voting: get-started/voting.md
        - Run a full node in testnet: get-started/run-node.md
        - Apply your node: get-started/apply-node.md
    # - TomoChain client:
    #   - Getting started: misc/wip.md
    #   - Contributing: misc/wip.md
    - Products:
      - TomoMaster: products/tomomaster/features.md
    #   - Contributing: misc/wip.md
      - TomoScan: products/tomoscan/features.md
      - TomoWallet:
        - Features: products/tomowallet/features.md
        - Voting with TomoWallet: products/tomowallet/voting.md
      - TomoBridge:
        - FAQ: products/tomobridge/faq.md
      - TomoIssuer:
        - Overview: products/tomoissuer/index.md
        - Term Of Condition: products/tomoissuer/termofcondition.md
        - Policy Privacy: products/tomoissuer/policyprivacy.md
    #   - Getting started: misc/wip.md
    #   - Contributing: misc/wip.md
    - Masternode:
      - Requirements: masternode/requirements.md
      - Detailed guide: masternode/masternode-setup-guide.md
      - Running a node with:
        - Binary: masternode/tomonative.md
        - Create-tomochain-masternode: masternode/create-tomochain-masternode.md
        - Tmn: masternode/tmn.md
        - Docker: masternode/docker.md
      - Applying for Masternode Candidacy: masternode/applying.md
      - Chaindata Snapshots: masternode/snapshot.md
  #   - Contributing: misc/wip.md
    #   - FAQ: misc/wip.md
    - Whitepapers and research:
      - Technical whitepaper: wp-and-research/technical-whitepaper.md
      - Sharding design paper: wp-and-research/sharding-paper.md
      - Economics paper: wp-and-research/economics-paper.md
      - Standard & Specification:
          - TRC21 Specification: wp-and-research/specs/trc21_standard.md
    - Developers guide:
        - Integrations:
          - TOMO Exchange/Wallet: developers/integrations.md
          - TomoChain Staking Governance: developers/staking-integrations.md
          - TRC20 Exchange/Wallet: developers/trc20-integrations.md
          - TRC21 Exchange/Wallet: developers/trc21-integrations.md
        - Working with TomoChain:
           - TomoChain private testnet setup: developers/tutoprivatenet.md
           - Useful manual CLI commands: developers/clicommands.md
           - Block header specification: developers/blockheader.md
           - Transaction types: developers/txtypes.md
        - DApps on TomoChain:
           - Deploy DApp on TomoChain: developers/dappdeploytuto.md
           - Deploy an ICO smart contract: developers/icosmartcontract.md
           - Using multisignature wallet: developers/multisigwallet.md
        - API Documentation: https://apidocs.tomochain.com
copyright: If you wish to improve this site, please <a href="https://github.com/tomochain/docs/issues/new"><i class="fa fa-github"></i> open an issue</a> or <a href="https://github.com/tomochain/docs/compare"><i class="fa fa-github"></i> send a pull request</a>.<br>TomoDocs v0.1.0. TomoChain Project 2018.
